### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by umaraziz0** [nithinpp69/react-native-circular-progress-indicator#39] opened 2022-03-29 11:40 UTC
Hello, I was trying to install this package but came across an error when trying to import the CircularProgress component:

```
// eslint caught this as 'unable to resolve path to module react-native-circular-progress-indicator'
import CircularProgress from 'react-native-circular-progress-indicator';
```

I have installed the required dependencies, including `react-native-svg` and `react-native-reanimated`, and did a `gradle clean`

Node version: `v16.13.0`

My `package.json`
```
"react": "17.0.2",
"react-native": "0.67.4",
"react-native-circular-progress-indicator": "^2.0.6",
"react-native-reanimated": "^2.5.0",
"react-native-svg": "^12.3.0",
``` 

Trying to run the app regardless returns these errors on the devtools:
```
D:\IMPORTANT\PROJECTS\krowdzReactNative\node_modules\react-native\Libraries\Core\ExceptionsManager.js:149 
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.
```

```
Error: Requiring module "node_modules\react-native-circular-progress-indicator\src\circularProgress\index.tsx", 
which threw an exception: Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.
```

```
Error: Requiring module "node_modules\react-native-reanimated\src\Animated.js", which threw an exception: 
Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

 Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time.
```

Any help would be greatly appreciated.

**Comment by goxr3plus** [comment] 2022-03-30 20:50
Yes passing from version 2.0.6 to 2.07 broke everything what is going on here , it's supposed to be a minor version an it has breaking changes not even a changelong ... 

@nithinpp69

**Comment by nithinpp69** [comment] 2022-03-31 04:49
@goxr3plus really sorry about that :(. Work has been a little heavy lately. I have reverted the changes and pushed a new version now. Will take care of the new changes and features soon. :)

**Comment by marcoturi** [comment] 2022-04-13 22:36
not fixed yet with 3.2.1

**Comment by Mohamed-kassim** [comment] 2022-04-20 23:04
Same issue here
```
error Unable to resolve module ./src/circularProgressBase from /Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/react-native-circular-progress-indicator/index.ts: 

Error: Unable to resolve module ./src/circularProgressBase from /Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/react-native-circular-progress-indicator/index.ts: 

None of these files exist:
  * node_modules/react-native-circular-progress-indicator/src/circularProgressBase(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native-circular-progress-indicator/src/circularProgressBase/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  1 | import CircularProgress from './src/circularProgress';
> 2 | import CircularProgressBase from './src/circularProgressBase';
    |                                   ^
None of these files exist:
  3 |
  4 | export default CircularProgress;
  5 | export { CircularProgressBase };
    at ModuleResolver.resolveDependency (/Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:107:15)
    at DependencyGraph.resolveDependency (/Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (/Users/haya/Desktop/Projects/Sahaab/onion-ts/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
info Run CLI with --verbose flag for more details.
  * node_modules/react-native-circular-progress-indicator/src/circularProgressBase(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native-circular-progress-indicator/src/circularProgressBase/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  ```

**Comment by Mohamed-kassim** [comment] 2022-04-21 00:03
@nithinpp69 the issue for me was
<img width="398" alt="Screen Shot 2022-04-21 at 2 03 01 AM" src="https://user-images.githubusercontent.com/37451755/164343883-c183ae80-5599-4e6c-aa97-b91d71de8824.png">
 circularProgressBase folder was CircularProgressBase
 i just renamed it changing the capital letter and it works now

**Comment by Mohamed-kassim** [comment] 2022-04-22 12:47
@marcoturi maybe he is using windows, as you know case sensitivity for files is not recognized for windows, only for UNIX Systems, also git doesn't catch renaming files directly
in this case, everything will work just fine for him.

**Comment by nithinpp69** [comment] 2022-04-22 13:28
@marcoturi Can you try removing your node-modules are install the lib again. I can't reproduce this error on my end.

**Comment by marcoturi** [comment] 2022-04-22 13:30
@nithinpp69 already tried, still present. Are you using windows to test as suggested by @Mohamed-kassim ?

**Comment by nithinpp69** [comment] 2022-04-22 13:33
No. I'm using mac and I do not have any issue using the package. The snack example given in the readme is also working fine ig.  Did you tried reinstalling with the latest version?

**Comment by nithinpp69** [comment] 2022-04-22 13:52
@marcoturi I've bootstrapped a small project. https://github.com/nithinpp69/circular-progress-playground.

**Comment by marcoturi** [comment] 2022-04-22 22:27
@nithinpp69 after deleting node_modules and yarn.lock the issue is gone. Thank you.

**Comment by nithinpp69** [comment] 2022-06-07 05:40
Closing as no further activity is recorded. Please feel free to reopen if you think this is still an issue.

**Closed by nithinpp69** 2022-06-07 05:40 UTC
